name: "I2C OLED Display"
description: "This addon lets you display to your I2C OLED for a Raspberry Pi with an I2C SSD1306 0.91\" 128x32 OLED."
version: "1.0.5"
slug: "i2c_oled_display"
startup: services
boot: manual
hassio_api: true
init: false
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - media:rw
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
options:
  Show_Static_Screen: true
  Show_Welcome_Screen: true
  Show_Splash_Screen: true
  Show_Network_Screen: true
  Show_CPU_Screen: true
  Show_Memory_Screen: true
  Show_Storage_Screen: true

  Welcome_Screen_Text: "Welcome to {hostname}"
  Static_Screen_Text: "Hassio verion {hassio.os.version} on {hostname} with IP {ip}"
  Graceful_Exit_Text: "Exited at {datetime}"

  Default_Duration: 10
  Scroll_Amplitude: 6
  DateTime_Format: "%d/%m/%Y %H:%M:%S"
  Static_Screen_Text_NoScroll: false
  Temperature_Unit: "C"
  Rotate: 0

  Welcome_Screen_Duration: 5
  Welcome_Screen_Limit: 2

  Splash_Screen_Duration: 5
  Splash_Screen_Limit: 0

  Network_Screen_Duration: 10
  Network_Screen_Limit: 0

  CPU_Screen_Duration: 5
  CPU_Screen_Limit: 0

  Memory_Screen_Duration: 5
  Memory_Screen_Limit: 0

  Storage_Screen_Duration: 5
  Storage_Screen_Limit: 0

  Debug_Mode: false
  I2C_bus: 1
  Screenshot: ''

schema:
  Show_Static_Screen: bool
  Show_Welcome_Screen: bool
  Show_Splash_Screen: bool
  Show_Network_Screen: bool
  Show_CPU_Screen: bool
  Show_Memory_Screen: bool
  Show_Storage_Screen: bool

  Welcome_Screen_Text: "str?"
  Static_Screen_Text: "str?"
  Graceful_Exit_Text: "str?"
 
  Default_Duration: int
  Scroll_Amplitude: "int?"
  DateTime_Format: "str?"
  Static_Screen_Text_NoScroll: bool
  Temperature_Unit: "list(C|F)?"
  Rotate: "int?"

  Welcome_Screen_Duration: "int?"
  Welcome_Screen_Limit: "int?"

  Splash_Screen_Duration: "int?"
  Splash_Screen_Limit: "int?"

  Network_Screen_Duration: "int?"
  Network_Screen_Limit: "int?"

  CPU_Screen_Duration: "int?"
  CPU_Screen_Limit: "int?"

  Memory_Screen_Duration: "int?"
  Memory_Screen_Limit: "int?"

  Storage_Screen_Duration: "int?"
  Storage_Screen_Limit: "int?"

  Debug_Mode: bool
  I2C_bus: "int(0,20)"
  Screenshot: "list(|/media)"
